SELECT * FROM CUSTOMERS
ORDER BY AGE ASC
ORDER BY AGE DESC

INSERT INTO CUSTOMERS
(NAME, SURNAME, AGE,BIRTHDAY)
VALUES
('JAMES','LÝÝN', 33,'1989-11-03')

UPDATE  CUSTOMERS SET
SURNAME='HARDEN'
WHERE AGE=33

DELETE FROM CUSTOMERS
WHERE NAME='JAMES'

