SELECT * FROM CUSTOMERS

ALTER TABLE CUSTOMERS
ADD PRÝCE ÝNT

ALTER TABLE CUSTOMERS
ADD PROPERTY  nvarchar(50)

SELECT * FROM CUSTOMERS
ORDER BY AGE ASC
ORDER BY AGE DESC

INSERT INTO CUSTOMERS
(NAME, SURNAME, AGE,BIRTHDAY, PRÝCE , PROPERTY)
VALUES
('FARUK','DERÝ', 32,'1997-8-03',5 ,'WATER')

UPDATE  CUSTOMERS SET
SURNAME='HARDEN'
WHERE AGE=33

DELETE FROM CUSTOMERS
WHERE NAME='AHMET'

DELETE FROM CUSTOMERS
WHERE  AGE < 40

SELECT DISTINCT SURNAME FROM CUSTOMERS

SELECT DISTINCT PROPERTY FROM CUSTOMERS



SELECT * FROM CUSTOMERS
WHERE AGE > 25

SELECT MIN(AGE)  FROM CUSTOMERS
SELECT MAX(AGE) FROM CUSTOMERS

SELECT SUM(PRÝCE) FROM CUSTOMERS
SELECT AVG(AGE) FROM CUSTOMERS


SELECT * FROM CUSTOMERS 
WHERE AGE >25 ORDER BY AGE DESC
