SELECT * FROM CUSTOMERS

ALTER TABLE CUSTOMERS
ADD PRÝCE ÝNT

ALTER TABLE CUSTOMERS
ADD PROPERTY  nvarchar(50)

SELECT * FROM CUSTOMERS
ORDER BY AGE ASC
ORDER BY AGE DESC

INSERT INTO CUSTOMERS
(NAME , SURNAME, AGE, BIRTHDAY, PRÝCE, PROPERTY)
VALUES
('SELÝN', 'RENK', 42, '2000-11-01', 15 ,'WATHER')


UPDATE CUSTOMERS
SET PRÝCE=20000
WHERE AGE=70

DELETE FROM CUSTOMERS
WHERE NAME='ALÝ'


DELETE FROM CUSTOMERS
WHERE  AGE < 40

SELECT DISTINCT SURNAME FROM CUSTOMERS

SELECT DISTINCT PROPERTY FROM CUSTOMERS



SELECT * FROM CUSTOMERS
WHERE AGE > 25

SELECT * FROM CUSTOMERS
WHERE PRÝCE > 5000

SELECT MIN(AGE)  FROM CUSTOMERS
SELECT MAX(AGE) FROM CUSTOMERS

SELECT SUM(PRÝCE) FROM CUSTOMERS
SELECT AVG(AGE) FROM CUSTOMERS


SELECT * FROM CUSTOMERS 
WHERE AGE >25 ORDER BY AGE DESC

SELECT * FROM CUSTOMERS
WHERE PROPERTY LIKE 'P%'

SELECT * FROM CUSTOMERS
WHERE PROPERTY ='WATHER' AND(SURNAME LIKE 'R%' OR SURNAME LIKE 'K%' )

SELECT *FROM CUSTOMERS
WHERE PROPERTY='WATHER' 
OR SURNAME='KOÇ'

SELECT * FROM CUSTOMERS
WHERE AGE BETWEEN 30 AND 70
ORDER BY AGE DESC





